// Generated by CoffeeScript 1.6.3
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var action, hexaLogo1, hexaLogo2, hexaPhoto, hexaTime, i, logos, photoControls, _fn, _i, _len, _ref;
    logos = document.getElementsByClassName('logo');
    hexaPhoto = new HexaFlip(document.getElementById('photo-demo'), {
      photos: (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 1; _i <=4 ; i = ++_i) {
          _results.push("./demo/images/" + i + ".jpg");
        }
        return _results;
      })()
    }, {
      size: 400,
      horizontalFlip: true
      
    });
    photoControls = document.getElementById('photo-controls');
    _ref = ['flipBack', 'flip'];
    _fn = function(action) {
      return photoControls.children[i].addEventListener('click', (function() {
        return hexaPhoto[action]();
      }), false);
    };
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      action = _ref[i];
      _fn(action);
    }

  }, false);

}).call(this);
/*
//@ sourceMappingURL=demo.map
*/
